#pragma once

// This file is generated by Python script.
// See: App/asset/generate_constexpr.py

namespace AssetImages
{
	constexpr StringView arrow_24x24 = U"asset/image/arrow_24x24.png";
	constexpr StringView beatrice_32x32 = U"asset/image/beatrice_32x32.png";
	constexpr StringView bookmark_16x16 = U"asset/image/bookmark_16x16.png";
	constexpr StringView brick_stylish_24x24 = U"asset/image/brick_stylish_24x24.png";
	constexpr StringView brick_stylish_light_24x24 = U"asset/image/brick_stylish_light_24x24.png";
	constexpr StringView bush_16x16 = U"asset/image/bush_16x16.png";
	constexpr StringView catfish_24x24 = U"asset/image/catfish_24x24.png";
	constexpr StringView clock_16x16 = U"asset/image/clock_16x16.png";
	constexpr StringView cursor = U"asset/image/cursor.png";
	constexpr StringView dango_wolf_24x24 = U"asset/image/dango_wolf_24x24.png";
	constexpr StringView dark_tree_16x16 = U"asset/image/dark_tree_16x16.png";
	constexpr StringView dark_tree_48x48 = U"asset/image/dark_tree_48x48.png";
	constexpr StringView folder_16x16 = U"asset/image/folder_16x16.png";
	constexpr StringView grass_tile_64x64 = U"asset/image/grass_tile_64x64.png";
	constexpr StringView grave_16x16 = U"asset/image/grave_16x16.png";
	constexpr StringView heart_vessel_24x24 = U"asset/image/heart_vessel_24x24.png";
	constexpr StringView helmet_16x16 = U"asset/image/helmet_16x16.png";
	constexpr StringView hourglass_16x16 = U"asset/image/hourglass_16x16.png";
	constexpr StringView light_bulb_16x16 = U"asset/image/light_bulb_16x16.png";
	constexpr StringView lion_32x32 = U"asset/image/lion_32x32.png";
	constexpr StringView magma_tile_24x24 = U"asset/image/magma_tile_24x24.png";
	constexpr StringView magnet_16x16 = U"asset/image/magnet_16x16.png";
	constexpr StringView mine_flower_16x16 = U"asset/image/mine_flower_16x16.png";
	constexpr StringView mixed_nature_16x16 = U"asset/image/mixed_nature_16x16.png";
	constexpr StringView omeme_patchouli_sun_16x16 = U"asset/image/omeme_patchouli_sun_16x16.png";
	constexpr StringView particle = U"asset/image/particle.png";
	constexpr StringView phine_32x32 = U"asset/image/phine_32x32.png";
	constexpr StringView pin_16x16 = U"asset/image/pin_16x16.png";
	constexpr StringView punicat_24x24 = U"asset/image/punicat_24x24.png";
	constexpr StringView rust_ferris_24x24 = U"asset/image/rust_ferris_24x24.png";
	constexpr StringView smile_mush_24x24 = U"asset/image/smile_mush_24x24.png";
	constexpr StringView solid_rock_16x16 = U"asset/image/solid_rock_16x16.png";
	constexpr StringView solt_16x16 = U"asset/image/solt_16x16.png";
	constexpr StringView stairs_24x24 = U"asset/image/stairs_24x24.png";
	constexpr StringView temple_knight_side_32x32 = U"asset/image/temple_knight_side_32x32.png";
	constexpr StringView test_tube_16x16 = U"asset/image/test_tube_16x16.png";
	constexpr StringView tex_aqua_noise = U"asset/image/tex_aqua_noise.png";
	constexpr StringView tex_cosmos_noise = U"asset/image/tex_cosmos_noise.png";
	constexpr StringView tree_16x16 = U"asset/image/tree_16x16.png";
	constexpr StringView tree_48x48 = U"asset/image/tree_48x48.png";
	constexpr StringView wing_16x16 = U"asset/image/wing_16x16.png";

	inline Array<StringView> GetKeys()
	{
		return {
			arrow_24x24,
			beatrice_32x32,
			bookmark_16x16,
			brick_stylish_24x24,
			brick_stylish_light_24x24,
			bush_16x16,
			catfish_24x24,
			clock_16x16,
			cursor,
			dango_wolf_24x24,
			dark_tree_16x16,
			dark_tree_48x48,
			folder_16x16,
			grass_tile_64x64,
			grave_16x16,
			heart_vessel_24x24,
			helmet_16x16,
			hourglass_16x16,
			light_bulb_16x16,
			lion_32x32,
			magma_tile_24x24,
			magnet_16x16,
			mine_flower_16x16,
			mixed_nature_16x16,
			omeme_patchouli_sun_16x16,
			particle,
			phine_32x32,
			pin_16x16,
			punicat_24x24,
			rust_ferris_24x24,
			smile_mush_24x24,
			solid_rock_16x16,
			solt_16x16,
			stairs_24x24,
			temple_knight_side_32x32,
			test_tube_16x16,
			tex_aqua_noise,
			tex_cosmos_noise,
			tree_16x16,
			tree_48x48,
			wing_16x16,
		};
	}
}

namespace AssetSes
{
	constexpr StringView arrow_step = U"asset/se/arrow_step.mp3";
	constexpr StringView attack1 = U"asset/se/attack1.mp3";
	constexpr StringView attack2 = U"asset/se/attack2.mp3";
	constexpr StringView break_helmet = U"asset/se/break_helmet.mp3";
	constexpr StringView damaged = U"asset/se/damaged.mp3";
	constexpr StringView enemy_find = U"asset/se/enemy_find.mp3";
	constexpr StringView fall_down = U"asset/se/fall_down.mp3";
	constexpr StringView floor_transition = U"asset/se/floor_transition.mp3";
	constexpr StringView game_over_back = U"asset/se/game_over_back.mp3";
	constexpr StringView game_over_front = U"asset/se/game_over_front.mp3";
	constexpr StringView item_enter = U"asset/se/item_enter.mp3";
	constexpr StringView item_use = U"asset/se/item_use.mp3";
	constexpr StringView recover_large = U"asset/se/recover_large.mp3";
	constexpr StringView recover_small = U"asset/se/recover_small.mp3";
	constexpr StringView scoop_move = U"asset/se/scoop_move.mp3";
	constexpr StringView scoop_start = U"asset/se/scoop_start.mp3";
	constexpr StringView stairs_close = U"asset/se/stairs_close.mp3";
	constexpr StringView stairs_step = U"asset/se/stairs_step.mp3";
	constexpr StringView take_item = U"asset/se/take_item.mp3";
	constexpr StringView title_environment = U"asset/se/title_environment.mp3";
	constexpr StringView title_start = U"asset/se/title_start.mp3";

	inline Array<StringView> GetKeys()
	{
		return {
			arrow_step,
			attack1,
			attack2,
			break_helmet,
			damaged,
			enemy_find,
			fall_down,
			floor_transition,
			game_over_back,
			game_over_front,
			item_enter,
			item_use,
			recover_large,
			recover_small,
			scoop_move,
			scoop_start,
			stairs_close,
			stairs_step,
			take_item,
			title_environment,
			title_start,
		};
	}
}

namespace AssetBgms
{
	constexpr StringView dear_my_rabbit = U"asset/bgm/dear_my_rabbit.mp3";
	constexpr StringView kazegasane = U"asset/bgm/kazegasane.mp3";
	constexpr StringView obake_dance = U"asset/bgm/obake_dance.mp3";
	constexpr StringView shiro = U"asset/bgm/shiro.mp3";
	constexpr StringView tokeitou = U"asset/bgm/tokeitou.mp3";
	constexpr StringView tokeitou_2023 = U"asset/bgm/tokeitou_2023.mp3";
	constexpr StringView yugata = U"asset/bgm/yugata.mp3";

	inline Array<StringView> GetKeys()
	{
		return {
			dear_my_rabbit,
			kazegasane,
			obake_dance,
			shiro,
			tokeitou,
			tokeitou_2023,
			yugata,
		};
	}
}
