[debug]
# title, lounge, play など
entry_point = ""

skip_transition = false
visualize_player_distance = false
initial_timelimit = 300.0

# 初期フロア (0: 無効)
initial_floor = 0

constant_floor = false
ura_enable = false

# Steam ストア用のグラフィックアセットをタイトル画面から作成する
# 例: "460x215"
title_graphic_asset_maker = ""

# プレイヤーの固定アイテム
# 例: [1, 13]
player_fixed_items = []
