[debug]
entry_point = ""
skip_transition = false
visualize_player_distance = false
initial_timelimit = 300.0
initial_floor = 1
constant_floor = false
ura_enable = false

# Steam ストア用のグラフィックアセットをタイトル画面から作成する
# 例: "460x215"
title_graphic_asset_maker = ""
