[debug]
# title, lounge, play など
entry_point = "title"

skip_transition = false
visualize_player_distance = false
initial_timelimit = 300.0

# 初期フロア (0: 無効)
initial_floor = 0

constant_floor = false
ura_enable = false

# チュートリアル: 移動方法から
tutorial_from_how_to_move = true

# Steam ストア用のグラフィックアセットをタイトル画面から作成する
# 例: "460x215"
title_graphic_asset_maker = ""

# プレイヤーの固定アイテム
# 例: [1, 13]
# Wing = 1,
# Helmet = 2,
# Pin = 3,
# Mine = 4,
# LightBulb = 5,
# Magnet = 6,
# Bookmark = 7,
# Explorer = 8,
# Grave = 9,
# Sun = 10,
# Tube = 11,
# Solt = 12,
# Rocket = 13,
player_fixed_items = []

# TIPS のテスト表示
tips_test = false

# 起動時に Steam の Stat のリセットを行う
steam_stat_reset = false

# Steam が起動していなくても実行可能
steam_no_require = false
