import os


def generate_constexpr(dir, ext):
    directory = os.path.dirname(os.path.realpath(__file__)) + "/" + dir
    files = [f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]

    png_files = [f for f in files if f.endswith(ext)]

    output_text = ""
    for png_file in png_files:
        var_name = png_file.replace(ext, "")
        output_text += f'constexpr StringView {var_name} = U"asset/{dir}/{png_file}";\n'

    output_text += "inline Array<StringView> GetKeys(){\nreturn{\n"
    for png_file in png_files:
        var_name = png_file.replace(ext, "")
        output_text += f'{var_name},\n'
    output_text += "};\n}\n"
    return output_text


if __name__ == "__main__":
    output_content = """
    #pragma once

    // This file is generated by Python script.
    // See: App/asset/generate_constexpr.py

"""

    output_content += "namespace AssetImages{\n"
    output_content += generate_constexpr("image", ".png")
    output_content += "}\n"

    output_content += "namespace AssetSes{\n"
    output_content += generate_constexpr("se", ".mp3")
    output_content += "}\n"

    output_content += "namespace AssetBgms{\n"
    output_content += generate_constexpr("bgm", ".mp3")
    output_content += "}\n"

    with open("../../Assets.generated.h", "w", encoding="utf-8") as file:
        file.write(output_content)
