[play]
bg_priority = -1000

[play.player]
move_duration = 0.3
anim_interval = 250
collider_padding = -8
focus_scale_large = 1.3
camera_offset_amount = 20.0
camera_offset_speed = 2.0
hitstopping_timescale = 0.1
dead_animation_offset_1 = "(0, -32)"
dead_animation_duration_1 = 0.7
dead_animation_offset_2 = "(0, -4)"
dead_animation_duration_2 = 0.3
dead_pause_duration = 1.0
scoop_rect_color_1 = "#6c95ebd0"
scoop_rect_color_2 = "#ffd217d0"
scoop_rect_color_3 = "#a2ff17d0"
scoop_move_duration = 0.5
warp_duration = 1.5
warp_jump_offset = "(0, -80)"

[play.en_slime_cat]
move_duration = 0.2
anim_interval = 250
floor_turn_likely = 3
pathway_turn_unlikely = 2
player_followiung_intensity = 4
lost_player_penalty = 1.0
baloon_offset_y = -32

[play.cave_vision]
default_vision_radius = 160
dark_color = "#3D30A2"

[play.ui_item_container]
center = "(0, 80)"

[play.debug]
visualize_player_distance = false
