[sukuu]
entry_point = "play"

[play.scene]
hitstopping_timescale = 0.1

[play.player]
move_duration = 0.3
anim_interval = 250
collider_padding = -8
focus_scale_large = 1.3
camera_offset_amount = 20.0
camera_offset_speed = 2.0
dead_animation_offset_1 = "(0, -32)"
dead_animation_duration_1 = 0.7
dead_animation_offset_2 = "(0, -4)"
dead_animation_duration_2 = 0.3
dead_pause_duration = 1.0
scoop_rect_color_1 = "#6c95ebd0"
scoop_rect_color_2 = "#ffd217d0"
scoop_rect_color_3 = "#a2ff17d0"
scoop_move_duration = 0.5
warp_duration = 1.5
warp_jump_offset = "(0, -80)"
initial_immortal = 2.5
recover_immortal = 1.5
helmet_offset = "(0, -10)"
helmet_animation = 200

[play.chara]
baloon_offset_y = -32

[play.enemy]
attacker_slime_cat = 30.0
attacker_knight = 45.0
magnet_penalty = 0.2

[play.en_slime_cat]
move_duration = 0.2
anim_interval = 250
floor_turn_pr = 0.75
pathway_turn_pr = 0.5
max_player_concern = 4
lost_player_penalty = 1.0
tire_count = 40
tire_penalty = 10

[play.en_knight]
move_duration = 0.5
min_move_duration = 0.1
speedup = 0.001
sleeping_sensing = 5
max_player_concern = 8
lost_player_penalty = 3.0

[play.item_pin]
move_duration = 0.05
rotation_speed = 20

[play.item_mine]
anim_interval = 150
scale_speed = 1440
scale_rate = 0.1

[play.item_magnet]
anim_interval = 200
scale_speed = 16.0
scale_rate = 0.3
lifetime = 15.0
roll_radius = 8
roll_jag = 8.0
roll_speed = 2.0
rotate_speed = 0.0

[play.cave_vision]
default_vision_radius = 160
dark_color = "#3D30A2"

[play.ui_minimap]
screen_point = "(100, 200)"
vision_render = 5
render_cell = 8
movable_color = "#70144840"
border_color = "#d0d0f0"
player_color = "#ffd14d"
item_color = "#1c9ee3"
stairs_color = "#5e8af7"

[play.ui_time_limiter]
circle_center = "(-160, 80)"
circle_radius = 40
circle_outer = 24
bg_back_scale = 2.0
bg_back_color = "#52555e"
back_scale = 1.1
back_color = "#7c7c7c"
main_color = "#ffc700"
damage_color = "#9d2b21"
empty_thickness = 2.0
empty_color = "#070707"
icon_size = 64
text_offset = "(-96, -12)"
rect_unit_width = 280

[play.ui_item_container]
base_vertical = 80
label_center = "(0, 80)"

[play.debug]
visualize_player_distance = false

[title.scene]

[title.background]
bg_color = "#313338"
camera_fov = 15
camera_initial_position = "(0, 20, 0)"
camera_target_position = "(0, 1, 0)"
camera_rotation_speed = 5
camera_follow_distance = 40.0
camera_follow_height = 40.0