[sukuu]
entry_point = "play"

[play]
bg_priority = -1000

[play.player]
move_duration = 0.3
anim_interval = 250
collider_padding = -8
focus_scale_large = 1.3
camera_offset_amount = 20.0
camera_offset_speed = 2.0
hitstopping_timescale = 0.1
dead_animation_offset_1 = "(0, -32)"
dead_animation_duration_1 = 0.7
dead_animation_offset_2 = "(0, -4)"
dead_animation_duration_2 = 0.3
dead_pause_duration = 1.0
scoop_rect_color_1 = "#6c95ebd0"
scoop_rect_color_2 = "#ffd217d0"
scoop_rect_color_3 = "#a2ff17d0"
scoop_move_duration = 0.5
warp_duration = 1.5
warp_jump_offset = "(0, -80)"

[play.en_slime_cat]
move_duration = 0.2
anim_interval = 250
floor_turn_likely = 3
pathway_turn_unlikely = 2
player_followiung_intensity = 4
lost_player_penalty = 1.0
baloon_offset_y = -32

[play.cave_vision]
default_vision_radius = 160
dark_color = "#3D30A2"

[play.ui_minimap]
screen_point = "(100, 200)"
vision_render = 5
render_cell = 8
movable_color = "#70144840"
border_color = "#d0d0f0"
player_color = "#ffd14d"
item_color = "#1c9ee3"
stairs_color = "#5e8af7"

[play.ui_time_limiter]
circle_center = "(-160, 80)"
circle_radius = 40
circle_outer = 24
bg_back_scale = 2.0
bg_back_color = "#52555e"
back_scale = 1.1
back_color = "#7c7c7c"
main_color = "#ffc700"
damage_color = "#9d2b21"
empty_thickness = 2.0
empty_color = "#070707"
icon_size = 64
text_offset = "(-96, -12)"
rect_unit_width = 280

[play.ui_item_container]
base_vertical = 80
label_center = "(0, 80)"

[play.debug]
visualize_player_distance = false

[title.scene]

[title.background]
bg_color = "#313338"
camera_fov = 15
camera_initial_position = "(0, 20, 0)"
camera_target_position = "(0, 1, 0)"
camera_rotation_speed = 5
camera_follow_distance = 40.0
camera_follow_height = 40.0