[debug]
entry_point = "play"
skip_transition = true
visualize_player_distance = false
initial_timelimit = 300.0
initial_floor = 4
constant_floor = false

[play.scene]
hitstopping_timescale = 0.1
slow_timescale = 0.3

[play.player]
move_duration = 0.3
anim_interval = 250
collider_padding = -8
focus_scale_large = 1.3
camera_offset_amount = 20.0
camera_offset_speed = 2.0
dead_animation_offset_1 = "(0, -32)"
dead_animation_duration_1 = 0.7
dead_animation_offset_2 = "(0, -4)"
dead_animation_duration_2 = 0.3
dead_pause_duration = 1.0
scoop_rect_color_1 = "#6c95ebc0"
scoop_rect_color_2 = "#ffd217c0"
scoop_rect_color_3 = "#a2ff17c0"
scoop_move_duration = 0.5
trail_color = "#ffbf00"
trail_size = 12
warp_duration = 1.5
warp_jump_offset = "(0, -80)"
initial_immortal = 2.5
recover_immortal = 1.5
helmet_offset = "(0, -10)"
helmet_animation = 200
light_bulb_duration = 12.0
explorer_enemies_duration = 15.0
tube_heal_amount = 90
solt_faint = 15.0

[play.chara]
baloon_offset_y = -32

[play.enemy]
attacker_slime_cat = 20
attacker_knight = 30
attacker_catfish = 15
attacker_crab = 25
attacker_lion = 35
magnet_penalty = 0.2

[play.en_slime_cat]
move_duration = 0.22
anim_interval = 250
floor_turn_pr = 0.75
pathway_turn_pr = 0.5
max_player_concern = 4
lost_player_penalty = 1.0
tire_count = 40
tire_penalty = 10

[play.en_knight]
move_duration = 0.49
min_move_duration = 0.11
speedup = 0.001
sleeping_sensing = 5
max_player_concern = 8
lost_player_penalty = 3.0

[play.en_catfish]
move_duration = 0.24
max_player_concern = 2
lost_player_penalty = 0.5
random_corner = 0.2
corner_pr = 0.8
meander_amount = 4

[play.en_crab]
move_duration_x = 0.15
move_duration_y = 0.35
max_player_concern = 5
lost_player_penalty = 1.5
corner_pr = 0.6

[play.en_lion]
move_duration = 0.5
tracking_duration = 0.25
max_player_concern = 7
lost_player_penalty = 1.5
corner_pr = 0.6
attack_duration = 0.3

[play.item_pin]
move_duration = 0.05
rotation_speed = 20

[play.item_mine]
anim_interval = 150
scale_speed = 1440
scale_rate = 0.1

[play.item_magnet]
anim_interval = 200
lifetime = 15.0
roll_radius = 12
roll_speed = 12.0

[play.item_grave]
lifetime = 10.0
anim_interval = 200
scale_speed = 16.0
scale_rate = 0.1

[play.item_sun]
move_duration = 0.1
rotation_speed = 0.2
movable_count = 40
blinking_start = 32

[play.cave_vision]
default_vision_radius = 160
dark_color = "#3D30A2"

[play.cave_snowfall]
dust_amount = 400
trail_color = "#c0c0ff"
visible_padding = 80
update_freq = 15

[play.damage_counter_effect]
appear_time = 0.1
outline = 0.8
font_size = 12
offset = -20
fade_offset = -12

[play.ui_minimap]
screen_point = "(100, 200)"
vision_render = 5
render_cell = 8
movable_color = "#70144840"
border_color = "#d0d0f0"
player_color = "#ffd14d"
enemy_color = "#f23f42"
item_color = "#1c9ee3"
stairs_color = "#5e8af7"

[play.ui_time_limiter]
circle_center = "(-160, 80)"
circle_radius = 40
circle_outer = 24
bg_back_scale = 2.0
bg_back_color = "#52555e"
back_scale = 1.1
back_color = "#7c7c7c"
main_color = "#ffc700"
penalty_damage_color = "#6c81a2"
enemy_damage_color = "#9d2b21"
heal_color = "#fefffb"
empty_thickness = 2.0
empty_color = "#070707"
icon_size = 64
text_offset = "(-96, -12)"
rect_unit_width = 280
pos_speed = 10.0

[play.ui_item_container]
base_vertical = 80
label_center = "(0, 80)"

[play.ui_floor_transition]
radial_duration = 1.0
line_duration = 0.7
line_thickness = 20.0
glyph_start = 0.3
glyph_appear = 1.2
glyph_y = -96
subtitle_y = 144
subtitle_color = "#9c9da0"
idle_duration = 0.5

[play.ui_current_floor]
padding = "(40, -20)"

[play.ui_dash_keep]
padding = "(-80, -64)"
radius = 40
default_color = "#25262b"
keep_color = "#ffc700"

[play.ui_game_over]
border_color = "#2c2727"
red_color = "#e84b3b"
main_size = 144
main_offset = -160
sub_size = 64
sub_offset = 128
line_width = 1280
line_color = "#3b3b3b"
line_offset_speed = 80.0
tips_size = 32
tips_color = "#878787"
tips_y = -160

[title.hud]
logo_scale = 2.8
logo_move_x = 24.0
logo_move_y = 64.0
prompt_font = 36.0
prompt_y = 320.0
record_outline = 0.1
record_font = 32.0
record_y = -480
button_size = "(196, 48)"
button_padding = "(-40, -20)"
button_color = "#525467"
button_space = 80

[title.background]
bg_color = "#313338"
camera_fov = 15
camera_initial_position = "(0, 20, 0)"
camera_target_position = "(0, 1, 0)"
camera_rotation_speed = 5
camera_follow_distance = 40.0
camera_follow_height = 40.0

[ending.background]
grad_height = 200
grad_color = "#d9ff3d"

[ending.hud]
margin_y = 120
text_size = 40
final_y = 120
final_size = 80

[tutorial.messenger]
bottom = 200
font_size = 42
fade_duration = 0.3

[tutorial.focus]
icon_scale = 1.5
icon_offset = "(-144, 0)"
icon_move = "(-120, 0)"
rect_size = "(240, 240)"
rect_thickness = 8.0
dot_speed = 20
